- name: Install Jdk
  become: yes
  apt:
    name:
      - openjdk-11-jre

- name: Add Jenkins key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repo
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name:
      - jenkins
    update_cache: yes

- name: download jenkins-plugin-manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.13/jenkins-plugin-manager-2.12.13.jar
    dest: $HOME/jenkins-plugin-manager.jar

- name: Add plugins file
  become: yes
  copy:
    src: plugins.yaml
    dest: /etc/plugins.yaml


- name: run the jenkins-plugin-manager
  become: yes
  command: java -jar jenkins-plugin-manager.jar --jenkins-version 2.263.4 --plugin-file /etc/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins

- name: Start Jenkins
  become: yes
  service:
    name: jenkins
    state: started
    enabled: yes
