- name: Install Jdk
  become: yes
  apt:
    name:
      - openjdk-11-jre

- name: Add Jenkins key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repo
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  become: yes
  apt:
    name:
      - jenkins
    update_cache: yes

- name: Start Jenkins
  become: yes
  service:
    name: jenkins
    state: started
    enabled: yes


# metadata_startup_script = <<SCRIPT
#   sudo apt update
#   sudo apt install openjdk-11-jre -y
#   curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
#       /usr/share/keyrings/jenkins-keyring.asc > /dev/null
#   echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
#       https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
#       /etc/apt/sources.list.d/jenkins.list > /dev/null
#   sudo apt-get update
#   sudo apt-get install jenkins -y
#   SCRIPT
