apiVersion: v1
kind: Service
metadata:
  name: {{ include "exemple.fullname" . }}
  namespace: default
spec:
  type: ClusterIP
  selector:
    {{- include "exemple.selectorLabels" . | nindent 6 }}
  ports:
    {{- range .Values.deployment.ports }}
    - name: port-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
    {{- end }}
