#!/bin/python3
from os import listdir
from os.path import isfile, join
import sys

def open_dir(path):
    onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]
    onlydir = [f for f in listdir(path) if not isfile(join(path, f))]
    if ("Makefile" in onlyfiles):
        return "C"
    if ("package.json" in onlyfiles):
        return "JavaScript"
    if ("requirements.txt" in onlyfiles):
        return "Python"
    if ("app" in onlydir):
        files = [f for f in listdir(path + "/app") if isfile(join(path + "/app", f))]
        if ("pom.xml" in files):
            return "Java"
        if (len(files) == 1 and files[0] == "main.bf"):
            return "Befunge"
    return "Unknown"

def main():
    if (len(sys.argv) != 2):
        print("Usage: check_language.py <path>")
        return
    print(open_dir(sys.argv[1]))

if __name__ == "__main__":
    try:
        main()
    except:
        print("Unknown folder")