FROM alpine:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY app .

RUN apk add git make gcc musl-dev
RUN git clone https://github.com/catseye/Befunge-93.git
RUN make -C Befunge-93
RUN mv Befunge-93/bin/bef bef
RUN rm -rf Befunge-93

CMD ["./bef", "main.bf"]