FROM alpine:latest

WORKDIR /app

ONBUILD COPY app .

ONBUILD RUN apk add git make gcc musl-dev bash
ONBUILD SHELL ["/bin/bash", "-c"]
ONBUILD RUN git clone https://github.com/catseye/Befunge-93.git
ONBUILD RUN make -C Befunge-93
ONBUILD RUN mv Befunge-93/bin/bef bef
ONBUILD RUN rm -rf Befunge-93

ONBUILD CMD ["./bef", "main.bf"]