FROM gcc:13.2

WORKDIR /app

ONBUILD COPY Makefile .
ONBUILD COPY app app

SHELL ["/bin/bash", "-c"]

ONBUILD RUN make
ONBUILD RUN make clean
ONBUILD RUN rm Makefile
ONBUILD RUN rm -rf app

ONBUILD CMD ["./compiled-app"]
