FROM maven:3.9.5

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY app .

ONBUILD RUN mvn package
ONBUILD RUN mv target/app.jar app.jar
ONBUILD RUN rm -rf target src pom.xml

ONBUILD CMD ["java", "-jar", "app.jar"]