FROM python:3.12

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY requirements.txt .
COPY app app

RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt

CMD ["python", "-m", "app"]