jenkins:
  systemMessage: "Welcome to the Whanos Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: "${USER_ADMIN_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "Admin group"
            description: "Whanos Administrator group"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

jobs:
  - file: link.groovy
  - file: build.groovy
