deployment:
  # Number of replicas, defaults to 1
  # Example:
  # replicas: 3
  replicas: 1

  # Pod resource requests and limits
  # Example:
  # resources:
  #   requests:
  #     memory: "128Mi"
  #     cpu: "500m"
  #   limits:
  #     memory: "256Mi"
  #     cpu: "1000m"
  resources: {}

  # TCP ports to expose on the pod's containers
  # Example:
  # ports: [3000, 8080]
  ports: []

