#!/bin/bash

echo " _       ____  _____    _   ______  _____"
echo "| |     / / / / /   |  / | / / __ \/ ___/"
echo "| | /| / / /_/ / /| | /  |/ / / / /\__ \ "
echo "| |/ |/ / __  / ___ |/ /|  / /_/ /___/ / "
echo "|__/|__/_/ /_/_/  |_/_/ |_/\____//____/  "
                                         
# Get the current git commit hash
current_commit_hash=$(git rev-parse HEAD)

# Check the language
echo $(/var/lib/jenkins/./check_language $1) > language.txt
language=$(cat language.txt)

# Format repository name
repository=$(echo "$1" | sed -e 's/.*Projects\///g' | sed -e 's/\/[^/]*$//g')
repository=$(echo "$repository" | tr '[:upper:]' '[:lower:]')
echo "In $repository, language is : $language"

# Check if language is known
if [[ "$language" == "unknown" ]]; then
    echo "Error: Unknown language detected."
    exit 1
fi

image_name="whanos-$repository-$language"

# Check if Dockerfile exists
if [ -f Dockerfile ]; then
    # Check if current commit hash is different from the previous commit hash
    previous_commit_hash=$(cat previous_commit_hash.txt)

    if [[ "$current_commit_hash" != "$previous_commit_hash" ]]; then
        # Update previous commit hash
        echo "$current_commit_hash" > previous_commit_hash.txt

        # Build Docker image
        cat /var/lib/jenkins/key.json | docker login -u _json_key --password-stdin https://$REGION
        docker build -t $image_name - < /var/lib/jenkins/images/$language/Dockerfile.base
        docker build -f /var/lib/jenkins/images/$language/Dockerfile . -t $image_name
        docker tag $image_name $REGION/$PROJECT_NAME/whanos-registry/$image_name:latest
        docker push $REGION/$PROJECT_NAME/whanos-registry/$image_name
    else
        echo "Skipping image build. No change in commit hash."
    fi
else
    image_name="$image_name-standalone"
    cat /var/lib/jenkins/key.json | docker login -u _json_key --password-stdin https://$REGION/
    docker build -f /var/lib/jenkins/images/$language/Dockerfile.standalone . -t $image_name
    docker tag $image_name $REGION/$PROJECT_NAME/whanos-registry/$image_name:latest
    docker push $REGION/$PROJECT_NAME/whanos-registry/$image_name
fi


# Deploy to Kubernetes
# PROJECT_NAME=$1
# image_name=$2
# WHANOS_FILE_PATH=$3
if [ -f $1/whanos.yml ] ; then
    echo "Deploying to Kubernetes..."
    sudo /var/lib/jenkins/kubernetes/terraformFiles/deploy.sh $repository $REGION/$PROJECT_NAME/whanos-registry/$image_name $1/whanos.yml
else
    echo "No whanos.yml file found in $1 ($1/whanos.yml)"
fi
